language: r
cache: packages
latex: false
warnings_are_errors: false
r_build_args: --no-build-vignettes
r_check_args: --as-cran --ignore-vignettes

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_: false
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

r_packages:
  - covr
  # This is the minimal set of R packages needed to run "R CMD check" on
  # the package.
  - assertthat
  - abind
  - mvtnorm
  - Rcpp
  - RcppArmadillo
  - RcppGSL
  - rmeta
  - plyr
  - testthat

r_github_packages: stephens999/ashr

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get -q update
  - sudo apt-get install -y libgsl-dev libomp-dev libgfortran-6-dev gfortran gcc-6 g++-6
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6

after_success:
  - Rscript -e 'covr::codecov()'

branches:
  only:
  - master
